# theme: jekyll-theme-minimal
title: Esther Ben Ami's Personal Site
description: Welcome to my personal website! (This site is a stub for future work.)
url: ""

relative_links:
  enabled:     true
  collections: false

kramdown:
    auto_ids: true

### Build settings ###
plugins:
  - jekyll-seo-tag
  - jekyll-menus
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-github-metadata


github:
  repository_url: https://github.com/Esther-Jane/personal-website
  repository_name: My Personal Site
  owner_url: https://github.com/Esther-Jane
  is_project_page: False
  is_user_page: True

repository: Esther-Jane/personal-website
baseurl: ""

# SEO Stuff
twitter:
  username: Lalin_Lua
  card: summary

# User settings
username: Esther Ben Ami
user_description: Writer

instagram_username: toukakat
twitter_username: Lalin_Lua
linkedin_username: Esther-Ben-Ami
github_username:  Esther-Jane
# medium_username: 
# medium_url:
email_form: https://google.com/
